name: media-server

services:
  init:
    build:
      context: ./init
    environment:
        GID: $GID
    volumes:
      - ${MEDIA_DRIVE}:/data
    restart: "no"

  deluge:
    build:
      context: ./deluge
      args:
        UID: $DELUGE_UID
        GID: $GID
        USER: deluge
    env_file: .env
    ports:
      - 8112:8112
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ${MEDIA_DRIVE}:/data
      - ${DELUGE_CONFIG}:/home/deluge/.config/deluge
