name: media-server

networks:
  media-server-network:

services:
  init:
    build:
      context: ./init
    environment:
        GID: $GID
    volumes:
      - ${MEDIA_DRIVE}:/data
    restart: "no"

  deluge:
    build:
      context: ./deluge
      args:
        UID: $DELUGE_UID
        GID: $GID
        USER: deluge
    env_file: .env
    ports:
      - 8112:8112
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - media-server-network
    volumes:
      - ${MEDIA_DRIVE}:/data
      - ${DELUGE_CONFIG}:/home/deluge/.config/deluge

  sonarr:
    build:
      context: ./sonarr
      args:
        UID: $SONARR_UID
        GID: $GID
        USER: sonarr
    env_file: .env
    ports:
      - 8989:8989
    depends_on:
      init:
        condition: service_completed_successfully
    networks:
      - media-server-network
    volumes:
      - ${MEDIA_DRIVE}:/data
      - ${SONARR_CONFIG}:/home/sonarr/.config/sonarr

  prowlarr:
    build:
      context: ./prowlarr
      args:
        UID: $PROWLARR_UID
        GID: $GID
        USER: prowlarr
    env_file: .env
    ports:
      - 9696:9696
    networks:
      - media-server-network
    volumes:
      - ${PROWLARR_CONFIG}:/home/prowlarr/.config/prowlarr

  radarr:
    build:
      context: ./radarr
      args:
        UID: $RADARR_UID
        GID: $GID
        USER: radarr
    env_file: .env
    ports:
      - 7878:7878
    networks:
      - media-server-network
    volumes:
      - ${MEDIA_DRIVE}:/data
      - ${RADARR_CONFIG}:/home/radarr/.config/radarr

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Paris
    ports:
      - 8191
    restart: unless-stopped
    networks:
      - media-server-network
